# Generated by Django 5.1.2 on 2024-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muslim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
    ]
